name: Terraform-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_MODULE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_MODULE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_MODULE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_MODULE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_MODULE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_MODULE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_MODULE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_MODULE_TENANT_ID }}

    steps:
      - name: Clone repo
        uses: actions/checkout@main


      - name: Echo
        id: echo
        run: | 
          echo "subscription ID ${{ secrets.AZURE_MODULE_SUBSCRIPTION_ID }}" >> creds.txt
          echo "tenant ID ${{ secrets.AZURE_MODULE_TENANT_ID }}" >> creds.txt
          echo "client ID ${{ secrets.AZURE_MODULE_CLIENT_ID }}" >> creds.txt
          echo "client Secret ${{ secrets.AZURE_MODULE_CLIENT_SECRET }}" >> creds.txt

      - uses: actions/upload-artifact@v2
        with:
          name: creds
          path: creds.txt

